version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
jobs:
  test:
    docker:
            - image: circleci/php:apache
              auth:
                username: cdinro73
                password: ZxC123DsA 
    working_directory: /var/www/html/test01
    steps:
    - checkout
    - run: apt install composer

workflows:
  test and deploy:
    jobs:
    - test
    - heroku/deploy-via-git:
        requires:
        - test
        filters:
          branches:
            only: master
