version: 2.1
orbs:
  heroku: circleci/heroku@1.0.1
jobs:
  test:
    docker:
    - image: circleci/php:apache
      auth:
        username: cdinro73
        password: $DOCKERHUB_PASSWORD 
    working_directory: /var/www/html/test01/tests
    steps:
    - checkout
   #- run: php test01.php
    - ls -R

workflows:
  test and deploy:
    jobs:
    - test:
        context: MyDocker01
    - heroku/deploy-via-git:
        context: MyHeroku01
        requires:
        - test
        filters:
          branches:
            only: master
